import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
import type { Metadata } from "next";
import { Urbanist, Poppins } from "next/font/google";
import "./globals.css";
import { TopLoaderProvider } from "@/providers/top-loader-provider";
import { ConvexAuthProvider } from "@/providers/convex-auth-provider";
import { ConvexProviderWrapper } from "@/providers/convex-provider";

const urbanist = Urbanist({
  variable: "--font-title",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-body",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexAuthNextjsServerProvider>
      <html lang="en">
        <body
          className={`${urbanist.variable} ${poppins.variable} antialiased`}
        >
          <TopLoaderProvider />
          <ConvexAuthProvider>{children}</ConvexAuthProvider>
        </body>
      </html>
    </ConvexAuthNextjsServerProvider>
  );
}
